name: 'Reliably GitHub Action'
description: 'Check for Reliably Advice and Suggestions'
author: 'Reliably'
branding:
  icon: "check-circle"
  color: "red"
inputs:
  command:
    description: 'Reliably command to execute'
    required: false
    default: 'discover'
  dir:
    description: 'Directory subject to verification'
    required: false
    default: '.'
  format:
    description: 'Report format'
    required: false
    default: 'simple'
  output:
    description: 'Write report to output file instead of stdout (default)'
    required: false
    default: ''
  args:
    description: "Additional arguments to pass to Reliably"
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/reliablyhq/cli/cli:latest'
  args:
  - ${{ inputs.command }}
  - --dir
  - ${{ inputs.dir }}
  - --format
  - ${{ inputs.format }}
  - --output
  - ${{ inputs.output }}
  - ${{ inputs.args }}
