name: 'reliably-action'
description: 'Run manifests analysis for reliability issues'
author: 'Reliably'
inputs:
  command:
    description: 'Reliably command to execute'
    required: false
    default: 'review'
  dir:
    description: 'Directory subject to verification'
    required: false
    default: '.'
#outputs:
#  result:
#    description: 'Outputs of Reliably'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/reliablyhq/cli/cli:latest'
  args:
  - ${{ inputs.command }}
  - --dir
  - ${{ inputs.dir }}
  - ${{ inputs.args }}
